/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo;

import java.net.MalformedURLException;

public class App {
    public void getGreeting() throws InterruptedException, MalformedURLException {
        // TestCases tests = new TestCases(); // Initialize your test class
        // Search_Amazon search = new Search_Amazon();
        // BookMyShow show = new BookMyShow();

        ImdbRatingAutomate rating = new ImdbRatingAutomate();

        // Automate_image image = new Automate_image();
        // Automate_Image_Url img = new Automate_Image_Url();
        // AuotmatNesttedFame frame = new AuotmatNesttedFame();
        // LinkedProfile profile = new LinkedProfile();
        // Automate_Window_handle window = new Automate_Window_handle();
        // Automate_Window_handle window = new Automate_Window_handle();

        // TODO: call your test case functions one after other here

        // tests.testCase01();
        // search.searchAmazon();
        // show.bookmyshow();
        // profile.linked();
        // frame.nestedFrame();
        // window.windowHandle();

        // image.automateImage();
        // img.automateimgUrl();

        rating.rating();

        // END Tests
        // search.endTest();
        // show.endTest();
        // profile.endTest();
        // image.endTest();
        // img.endTest();
        // frame.endTest();
        // window.endTest();
        rating.endTest();
        // tests.endTest(); // End your test by clearning connections and closing
        // browser
    }

    public static void main(String[] args) throws InterruptedException, MalformedURLException {
        new App().getGreeting();
    }
}
